jdk:
- openjdk8
language: scala
scala:
- 2.13.1
- 2.12.11
- 2.11.12
jobs:
  include:
  - stage: check
    env: ISOLATED=true
    scala: 2.13.1
    script: sbt scalafmtCheckAll || { echo "[error] Unformatted code found. Please
      run 'scalafmtAll' and commit the reformatted code."; false; }
    name: Code style check (fixed with `sbt scalafmtAll`)
  - script: sbt scalafmtSbtCheck || { echo "[error] Unformatted sbt code found. Please
      run 'scalafmtSbt' and commit the reformatted code."; false; }
    name: Build code style check (fixed with `sbt scalafmtSbt`)
  - stage: docs
    name: Push documentation to ghpages
    env: ISOLATED=true
    scala: 2.13.1
    script:
    - git config --global user.name "$USER"
    - git config --global user.email "$TRAVIS_BUILD_NUMBER@$TRAVIS_COMMIT"
    - openssl aes-256-cbc -K $encrypted_91e912197555_key -iv $encrypted_91e912197555_iv
      -in .travis/secrets.tar.enc -out .travis/secrets.tar -d
    - tar xv -C .travis -f .travis/secrets.tar;
    - chmod 600 .travis/local.travis-deploy-key
    - eval "$(ssh-agent -s)"
    - ssh-add .travis/local.travis-deploy-key
    - sbt ";docs/makeSite; docs/ghpagesPushSite"
  - stage: deploy
    name: Deploy to Bintray
    script:
    - openssl aes-256-cbc -K $encrypted_91e912197555_key -iv $encrypted_91e912197555_iv
      -in .travis/secrets.tar.enc -out .travis/secrets.tar -d
    - tar xv -C .travis -f .travis/secrets.tar;
    - mkdir -p $HOME/.sbt/gpg && cp .travis/local.pubring.asc $HOME/.sbt/gpg/pubring.asc
      && cp .travis/local.secring.asc $HOME/.sbt/gpg/secring.asc
    - sbt ++$TRAVIS_SCALA_VERSION releaseEarly
stages:
- name: check
  if: NOT tag =~ ^v
- test
- name: docs
  if: tag =~ ^v
- name: deploy
  if: tag =~ ^v
before_cache:
- rm -fv $HOME/.ivy2/.sbt.ivy.lock
- rm -fv $HOME/.sbt/ghpages
- rm -fv $HOME/.sbt/gpg
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt        -name "*.lock"               -print -delete
cache:
  directories:
  - "$HOME/.cache/coursier"
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot"
  - "$HOME/.sbt/launchers"
env:
  global:
  - secure: XtzjqXGAEOrMBszXF0tiEFR110+BbpArm3pu3WO6q8MPrC17laBdq6AZM1aANUT8fy53lI7Gu/Sj26z2nnIvcqtsATnB3zLdHoznmkB+1QMrT5kxh34BH9csaLDa2mMN1WAL6cKLEMUJ9JaDlxsHHEjn+63N81G9PM0pGZttZxqoOO9Ls9CU2TZb8zYYU3VP9lcRbZWP8ncckauNjbopUfXQT6myKeR3Nzsp7WSfH8wcvF7PQgNbX5XubihPKHd/dS9sGIbJQmVGZgVM4jwWWBusBn13mBjzIIbpgPeR8b3w3BRlUi952VbSBR6IrdYuG/Tkik4tYQp/9UCpMPld9AcZqFb7VzArf6DzwirMGkY5Wt5EKFeobJOX6IFZfI9kYCfdP0uu36K98LZTMU6pDq8Gh8pexvibMEiMXwkMHMUSyN5MYzBqbENSn+mNeXlV0eMy4V1BRYD5zHZma1/se0HwnnC6a9WFPBZT70//eAb96M5nEBJZiFttGeEIPCmwUWI6yvGEF3Cjslz9j59QBGoEke3JSb/7ssCtOKnI0CnnK/7rMmOxvSeMkhVCedblkoCOQNJKq74WOKPtq7RaFYDOdgH89kUmvW8tOVFPZRHMBH9urEKzSBQFiY8XQQ4NOhvdC899TpMEww9qvT20/xTMe/qYCRk3tmsF/5U7b5w=
  - secure: KnHZ2fmpUa14FVGLuPsqMIkkTKVbzA9xDTaXSpRvnIGdjjr+fc8bmrziUQtaTnhdR+GW7xIaK5cibSpRF0Ado4p9yg3DAJZgpjOPp14mRQzstPbuGEaXK4qZZ2Z77KsKxZXLqgyTyUtkNjmm8fcbSR/eqO9JAupiv3Hvt+bi4r45SdC1EhCj04YYs8d5OOYKS7EyfAS30neuzj9ZhHVsPqFQtwK+NLWv+f4pAVZaiSH/Dg45XUOumCytnQF3cdWba5Pp1pmwBNCxr/BloVljLi1MBF6kBjvrRaUt4Z58fn38HNyzJRdhFkCANTRVjH431Xc7YNXtGrUEBxCUoWy6G/yVJjz4msXrHUxfp/BlCuWdENJH8OTys3IdqmX2t0BjRksMGhwC3hhcsZ6hsrENIQIRfr8pwG6XswVVt60bsxmRPmdHfZmOLZJQu4y3nedsPfd8C2nfJt+2GLpwLv7BmIIFfTP/oqeNWRRqiwgp8gtyK/FG2qFtEcZ8JCYo1+A5g/3zKjoQSFRosaUnpO+KqyO0JJf6A51RBAVGCtGpVuZULFixbfjyiu20YBinR0khmROqw9IxV3V3dwNlTjZ9dapZcfuozi0OgrS/RFSgmMkgP4CbPD+K5L9iwxMVkW7JoSBtTTX5WUV4tbpwzSO5Bp58dRPEWqecwhF585gVYRw=
  - secure: cdFKNEaJmCRaJgN+olGm/syygBKc6i1byyp9sGj31pcP1DhSdsCGbSzL+DTpVH/R/ngRil4t/jlVIvo9zNWqg4XZTqgRdMfzA4RPW9s97VqzaOYnCfzNJY5W2U9qjr9lIypzk6w5Ia3zMp87bEtYFeP1l8C4PVzQTBE7qvZ/nW5SkNSPNJoHwN8f/t2L35OBGxC9p67Lp5N93z5FY87OySyLbpzZqnPUeA6E+zTUgWyqN3BuvY6IsiiAYQHEyDsPXAw7H1qc9UCxMpJt80sTF0m6rpAJv2vH4Yv+hTL5OnDJeHLuG+Tdg9mzH1xyW3nI+WS/I7dVhfPAdaf6HeeUXZqV/8iPuvJt37W0vgPMtcBbKgjOescP3kdfiq8+Vsr+5tXPrf7/UK7GgX6aBYHnD9xYS0DacS2ckR1OCe3FW24yEXKaL6dG8++pTBygc9OLi1pHyXosJBeK2MHp2U8um2c6flpaIQs3q6yEbVfLPdNMO0KKKvgpgVwV/x5LBE0o/k7oLLFWNlp/LIP/z5hcm5rZDY8ZZ9XKpUEHPKnym2lAT2Og5sPxK/nd412VMIWGa+4qjeSYwwdxmYl9/tBRnXQQtXMTIDTcZyRLI/oPlcgmb5OoC/HKm2R+dseK8wX2H2ZzF/qCjC9jBuIrDHoVaPAU1LP0Jt5e5fREW54v6Qc=
